# Staging ArgoCD Applications

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: staging
    app: fleet
spec:
  project: default
  source:
    repoURL: https://github.com/sangkips/fleet-infra.git
    targetRevision: HEAD
    path: charts/fleet
    helm:
      valueFiles:
        - values.yaml
        - ../../environments/staging/fleet-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fleet-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: investify-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: staging
    app: investify
spec:
  project: default
  source:
    repoURL: https://github.com/sangkips/fleet-infra.git
    targetRevision: HEAD
    path: charts/investify
    helm:
      valueFiles:
        - values.yaml
        - ../../environments/staging/investify-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: investify-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
